### ISSUE TITLE
Auto-stow after placement

### ISSUE THREAD

**Issue by GalexY727** [Patribots4738/2023-Summer-Robot#2]
After the robot has placed a game piece, automatically stow the pivot using PlacementConstants.PLACEMENT_POSITIONS(forward / behind) [PlacementConstants.RESET_INDEX]

This is simply QoL, and not required. I would like some discussion to go into if this should be added in the first place or not.

Please note, @Jacob1010-h, @GalexY727 and @RudyG252 are not allowed to directly contribute to this issue. I would like to see if other people are able to tackle this one. Best of luck and please reply here with your thoughts on if it should be incorporated or not!

**Comment by PatribotsProgramming** [comment]
If this were to be added to the robot code, then directly as "Right Trigger" is pressed the pivot will automatically reset to the Reset position.
This would be more efficient because the operator would not have to constantly reset the pivot after scoring.
The only issue that I could see was that the pivot could possibly reset before the cube is released. This would negatively affect the trajectory of the cube. 
I have concluded that if this were to be added, some type of timer could be implemented to delay the automatic pivot reset, in order to prevent this issue.

-Zac
