### ISSUE TITLE
Add some more auto paths

### ISSUE THREAD

**Issue by jacueblol** [Patribots4738/2023-Summer-Robot#8]
We shouldn't need anything extra for this other than `Charge` but what do you think @GalexY727 ?

**Comment by GalexY727** [comment]
Thankfully due to us not having any cameras we can run a place pickup place 2-p auto that can work for both grid index 2 and 8, since the piece is the same distance away from both. One thing that is worth mentioning is that we would manually have to mark the 6 inch offset (ideally on the robot) to make sure we set the bot up on the right distance on the Y axis of the field that the bot is from the piece, just in case we want to be that extra bit more precise in our path. That way we can move straight back and pickup the piece, then reverse and score it.

**Comment by GalexY727** [comment]
A backup path I had thought of adding is one that uses a timer to go forward for X seconds, then reverses on another timer (ideally X/2 seconds) and goes from there.

**Comment by jacueblol** [comment]
> A backup path I had thought of adding uses a timer to go forward for X seconds, then reverses on another timer (ideally X/2 seconds) and goes from there.

This shouldn't be too hard; it could be put together pretty quickly too, without the use of our currently buggy pathplanner

**Comment by jacueblol** [comment]
I would love to do something more accurate with pathplanner, however, time is of the essence, and after I calibrate and I still don't have time, then something janky might just need to be implemented

**Comment by PatribotsProgramming** [comment]
The auto path is now fixed and ready!!
